"""Direct SMTP email OTP — makes authentication fully self-contained (Supabase optional).

Flow: generate a cryptographically-random 6-digit OTP (secrets module — NOT predictable,
NOT generated by any email provider) → store only its hash with a 5-minute TTL →
email via any SMTP provider (Brevo/Gmail/Resend are just delivery channels) →
verify with attempt limiting.
"""
import hashlib
import logging
import secrets
import smtplib
from email.message import EmailMessage

from app.core.config import get_settings
from app.services import cache_service

logger = logging.getLogger(__name__)
settings = get_settings()


def _hash(email: str, code: str) -> str:
    return hashlib.sha256(f"{email.lower()}:{code}".encode()).hexdigest()


def generate_and_store_otp(email: str) -> str:
    """Create a crypto-secure 6-digit OTP, store its hash with a TTL, return the code."""
    code = f"{secrets.randbelow(1_000_000):06d}"
    cache_service.cache_set(
        "otp", [email.lower()], _hash(email, code), ttl=settings.otp_expire_minutes * 60
    )
    # reset attempts counter
    cache_service.cache_set("otp_attempts", [email.lower()], 0, ttl=settings.otp_expire_minutes * 60)
    return code


def verify_otp(email: str, code: str) -> dict:
    """Check the code. Limited attempts prevent brute-forcing."""
    key = email.lower()
    stored = cache_service.cache_get("otp", [key])
    if not stored:
        return {"ok": False, "error": "OTP સમાપ્ત થઈ ગયો છે. નવો OTP મંગાવો."}

    attempts = cache_service.cache_get("otp_attempts", [key]) or 0
    if attempts >= settings.otp_max_attempts:
        # consume the OTP so further attempts require a fresh code
        cache_service.cache_set("otp", [key], "consumed", ttl=60)
        return {"ok": False, "error": "ઘણા ખોટા પ્રયાસ થયા. નવો OTP મંગાવો."}

    if _hash(email, code.strip()) == stored:
        # consume the OTP (single use)
        cache_service.cache_set("otp", [key], "consumed", ttl=60)
        return {"ok": True}

    cache_service.cache_set("otp_attempts", [key], attempts + 1,
                            ttl=settings.otp_expire_minutes * 60)
    left = settings.otp_max_attempts - (attempts + 1)
    return {"ok": False, "error": f"OTP ખોટો છે. {left} પ્રયાસ બાકી."}


def _send_via_brevo_api(email: str, code: str) -> dict | None:
    """Send via Brevo HTTPS API (no IP restrictions, ideal for serverless).
    Returns None if BREVO_API_KEY is not configured."""
    if not settings.brevo_api_key:
        return None
    import requests

    sender = settings.smtp_from_email or "gyansathi@example.com"
    payload = {
        "sender": {"name": settings.smtp_from_name or "Gyan Sathi", "email": sender},
        "to": [{"email": email}],
        "subject": f"{code} — Gyan Sathi લોગ ઇન કોડ",
        "textContent": (
            f"નમસ્તે!\n\nતમારો Gyan Sathi લોગ ઇન કોડ: {code}\n\n"
            f"આ કોડ {settings.otp_expire_minutes} મિનિટ માટે માન્ય છે.\n"
            "જો તમે આ વિનંતી કરી નથી, તો આ ઈમેલ અવગણો.\n\n— Gyan Sathi"
        ),
        "htmlContent": (
            f'''<div style="font-family:sans-serif;max-width:480px;margin:auto;text-align:center;
      border:1px solid #e2e8f0;border-radius:16px;padding:32px">
  <h2 style="color:#122948;margin:0">Gyan Sathi</h2>
  <p style="color:#64748b;font-size:14px">તમારો અભ્યાસ, અમારો સાથી</p>
  <p style="color:#334155">તમારો લોગ ઇન કોડ:</p>
  <p style="font-size:36px;font-weight:800;letter-spacing:8px;color:#1B62B5;margin:12px 0">{code}</p>
  <p style="color:#94a3b8;font-size:12px">{settings.otp_expire_minutes} મિનિટ માટે માન્ય ·
     જો તમે વિનંતી કરી નથી તો આ ઈમેલ અવગણો.</p>
</div>'''
        ),
    }
    try:
        resp = requests.post(
            "https://api.brevo.com/v3/smtp/email",
            headers={"api-key": settings.brevo_api_key,
                     "Content-Type": "application/json",
                     "accept": "application/json"},
            json=payload, timeout=15,
        )
        if resp.status_code in (200, 201, 202):
            logger.info("OTP email sent via Brevo API to %s", email)
            return {"sent": True}
        logger.error("Brevo API failed: %s %s", resp.status_code, resp.text[:200])
        return {"sent": False, "reason": f"brevo_api_{resp.status_code}: {resp.text[:120]}"}
    except Exception as exc:
        logger.error("Brevo API error: %s", exc)
        return {"sent": False, "reason": str(exc)[:200]}


def send_otp_email(email: str, code: str) -> dict:
    """Send the OTP email via Brevo API (preferred) or SMTP. Returns {sent: bool, reason?}."""
    via_api = _send_via_brevo_api(email, code)
    if via_api is not None:
        return via_api

    if not settings.smtp_host or not settings.smtp_user:
        return {"sent": False, "reason": "smtp_not_configured"}

    msg = EmailMessage()
    msg["Subject"] = f"{code} — Gyan Sathi લોગ ઇન કોડ"
    msg["From"] = f"{settings.smtp_from_name} <{settings.smtp_from_email or settings.smtp_user}>"
    msg["To"] = email
    msg.set_content(
        f"""નમસ્તે!

તમારો Gyan Sathi લોગ ઇન કોડ:

    {code}

આ કોડ {settings.otp_expire_minutes} મિનિટ માટે માન્ય છે.
જો તમે આ વિનંતી કરી નથી, તો આ ઈમેલ અવગણો.

— Gyan Sathi (તમારો અભ્યાસ, અમારો સાથી)
"""
    )
    html = f"""<div style="font-family:sans-serif;max-width:480px;margin:auto;text-align:center;
      border:1px solid #e2e8f0;border-radius:16px;padding:32px">
  <h2 style="color:#122948;margin:0">Gyan Sathi</h2>
  <p style="color:#64748b;font-size:14px">તમારો અભ્યાસ, અમારો સાથી</p>
  <p style="color:#334155">તમારો લોગ ઇન કોડ:</p>
  <p style="font-size:36px;font-weight:800;letter-spacing:8px;color:#1B62B5;margin:12px 0">{code}</p>
  <p style="color:#94a3b8;font-size:12px">{settings.otp_expire_minutes} મિનિટ માટે માન્ય ·
     જો તમે વિનંતી કરી નથી તો આ ઈમેલ અવગણો.</p>
</div>"""
    msg.add_alternative(html, subtype="html")

    try:
        if settings.smtp_port == 465:
            with smtplib.SMTP_SSL(settings.smtp_host, settings.smtp_port, timeout=15) as server:
                server.login(settings.smtp_user, settings.smtp_password)
                server.send_message(msg)
        else:  # 587 STARTTLS
            with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=15) as server:
                server.starttls()
                server.login(settings.smtp_user, settings.smtp_password)
                server.send_message(msg)
        logger.info("OTP email sent to %s", email)
        return {"sent": True}
    except Exception as exc:
        logger.error("SMTP send failed: %s", exc)
        return {"sent": False, "reason": str(exc)[:200]}
